{% set name = "nodeenv" %}
{% set version = "1.3.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "87a2103abf5412c0cb5370109697f211d4b6014adbbf3c4efbe2bd4df30e0e3c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/ekalinin/nodeenv/archive/{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - nodeenv = nodeenv:main
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - nodeenv --help
    # skip test_predeactivate_hook test because it fails on py36
    # See: https://github.com/ekalinin/nodeenv/pull/200
    - pytest tests -k-test_predeactivate_hook
  requires:
    - pytest
    - mock
    - coverage
  source_files:
    - tests

about:
  home: https://github.com/ekalinin/nodeenv
  license: BSD 3-Clause
  license_family: BSD
  license_file: ''
  summary: Node.js virtual environment builder

extra:
  recipe-maintainers:
    - nicoddemus
