{% set name = "nodeenv" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nodeenv-{{ version }}.tar.gz
  sha256: 6ec12890a2dab7946721edbfbcd91f3319c6ccc9aec47be7c7e6b7011ee6645f

build:
  number: 0
  # Need to avoid error: setuptools-scm was unable to detect version !!!
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - nodeenv = nodeenv:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
    - setuptools-scm
  run:
    - python
    - setuptools  # depends on pkg_resources at runtime

test:
  source_files:
    - tests
  imports:
    - nodeenv
  commands:
    - pip check
    - nodeenv --help
    # Skip test_smoke: https://github.com/ekalinin/nodeenv/issues/360
    - pytest -vv tests -ra -k "not test_smoke"
  requires:
    - pip
    - pytest
    - mock
    - coverage

about:
  home: https://ekalinin.github.io/nodeenv/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Node.js virtual environment builder
  dev_url: https://github.com/ekalinin/nodeenv
  doc_url: https://github.com/ekalinin/nodeenv

extra:
  recipe-maintainers:
    - nicoddemus
