{% set name = "nodeenv" %}
{% set version = "1.3.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "51711cde99729c6a6d8a03b4abb03347609f861c14f2ff9a8926a9d83d9647b4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/ekalinin/nodeenv/archive/{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - nodeenv = nodeenv:main
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - nodeenv --help
    # skip test_predeactivate_hook test because it fails on py36
    # See: https://github.com/ekalinin/nodeenv/pull/200
    - pytest tests -k-test_predeactivate_hook
  requires:
    - pytest
    - mock
    - coverage
  source_files:
    - tests

about:
  home: https://github.com/ekalinin/nodeenv
  license: BSD 3-Clause
  license_family: BSD
  license_file: ''
  summary: Node.js virtual environment builder

extra:
  recipe-maintainers:
    - nicoddemus
