travis:
  secure:
    BINSTAR_TOKEN: tkjtH9fk/gOCTmsEmV6YSch7BD5ya5o2j2sER/jcALRcZfAj+f5JnwHQxGA0SAE03e3UVCsJG/STd/8tSnEPXIy5WhB6Ul3j+0YdfZ8gvuwU/oOXdYFSu5AyLWnxGsENYT3nHkGiSACmcqbA5fYQu1jP7nfOvCpLSCuzXw2g+PiGRp8X8n7mjrP6s0MAjnjq64yqxuvyG1fyfAfNwKvtgs/RMc1SeGVGwlPPAtzHE9cKOy82JrjBhHLYip4QIrkEwPGOl+JcThdCS5FL6LZ8kSuvEoesdrVLqWKQRJuQUe6LvlO+hoHqKNnMb77RWsbIjCS47Uc/0PzV9ZipKwN3iB9wmhkbI1M7AEkft3cqxnzlxWvYJdcMt56uvDmBpQDegSLZ/jtVbyvXFuxCDw8N7vlSHrARmkOpwTo7bqXghqdfTHLTP/qx50NJJxKjrJZLLphX48AmFRvOk6TSI7rZVLUWZYi7+aSBMe2Soiu18uHA8lD2U7f6iknV3cYA4inrhdR2FMhSpCd9whUoA1DkalVaphTo7NUAt+nD/8l7/YQvyKC8akoHAzuDhAZJ9wO/XwtXiX3rfs4xSn2Evibevc/RXppWObCB+YHzDUOnLNK63ViuZCe5EsQHdYF9LcbROWezUbPsePlXiXFmr4M9cs0ymEWza3gJN6VIEcVOGFE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
