travis:
  secure:
    BINSTAR_TOKEN: e9sKjtHYPuG2jGTNDUhecLNbwUtmh5qc32cKO455hBP05w80qXEduQz1QPVhoc/EwXjvhgJREYa3mOGJDJ6JsjAQukDA4BojWFl3gkDXQY4ovMz0momUtQ7LiVjfdNSoC3zJ+IhAXRlId88Vko8OgfgjOWJeCT6ghbSlMZq0IDUlOMBC4WYn9XBrfeb/HSLBAh8Z8PVrv4ZH1u4C4DyeFifeY99rhR0p9xY1rOa6TQSATG8ASj76vhzsCMDWShwg10Hh8Tf0rqHR9osPpr41xiPbrN2tkkGNnHdbXVD1f4enMnipF+IF2ZJSSepNyxvRVZMELMs0OpWZUrA+BVBAO8h+3XQUDgHn/Hf5BwPw2iowSVfzxZKRH0MeUc1oQlF3deA9QMQadt42dIncL8fCnTgsOqyrd+vf7C4SKeS9PTltR2bDgS5Lq7oiqp55BybRexRqKkgAH5HTUBsSsoRa5BzwHNnVrEHHj/6GeIPEiD5p2t25hPucZZ9t8t+ajgHQ6GgzGoMzLIyX+dBbgUMF0HmQvlLN/GVbD5Jmz8ow+zblkNLpc2JydFEpXdv2yKO2TpLizb6OCZyjqPJq6kWp/gWCvhG3IL/fkSZYK+xHK1fqEmUf+6a7qbIHm9+Didz8HNCARUDMqGeINGusAMaEQPrn/Hm8+x5W3glGhXF6fec=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
